apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: argocd
    homelab.local/OwnedBy: ElPoshoX
resources:
- base/argocd-namespace.yaml
- base/argocd-redis-secret.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.4/manifests/install.yaml
- base/argocd-ingress.yaml
- base/argocd-platform-project.yaml
- base/argocd-pvc.yaml


patches:
- path: overlays/production/argocd-cm.yaml
- path: overlays/production/argocd-server-service.yaml
- path: overlays/production/argocd-cmd-params-cm.yaml
- path: overlays/production/argocd-rbac-cm.yaml

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argocd/argocd
  newTag: latest
