apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-private-repo-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: private-repo-creds
          annotations:
            argocd.argoproj.io/secret-type: repo-creds
          stringData:
            type: ENC[AES256_GCM,data:2VWI,iv:R+sW3dEaHt0nu97MeEbY1fkQnVUIgD1N0g8CS/2zp4Q=,tag:Cn8rRGKqEKsYZDr3KI0oTg==,type:str]
            url: ENC[AES256_GCM,data:6x7MrZn7gZbdAIFZr5SAttxio/48fcaLGziV,iv:hhB0xTekGhXDvr0+TSOx8WOnIWLhrtUhyszL76oWwaM=,tag:hNfBV+y+VGmYDLVf7TxW3Q==,type:str]
            password: ENC[AES256_GCM,data:6YPy22gmvbWDBkxfNwdaXxyj12x8+zR9OA0Se8raPFoi3H/po53R+Q==,iv:RJMhOGmYWlhTQQj/P/Rd/bjYVwrCwk3tgMPLcerjam4=,tag:4yaZ9hCLMt9lgYaIBZ0LRg==,type:str]
            username: ENC[AES256_GCM,data:HmxKy5K53c8=,iv:DaIYpB31rypq+nDrdtqs2HmnyP2FVgwppMuMjekIM20=,tag:Gv/NHxkQjVh9aKWUuUHUog==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QTVDak8rdFdKQUp3WDJ5
            SUlTeit5eTRJZUZiUzBINU1TWEdreW83WHpJCjBjcEh3UXYzOEVSMDJLL2RoUEtU
            ZXZYYTlKVGwzZ0gzaFdZTVI2bG9HQUEKLS0tIGozcDVXWitxbTZTOXdTMkMrSnd1
            S0JNRFVDQ0ZsK3JMOW1PRy95dlV5MVUK7yltIqJSzFOqdha3XHtbV3LvIKQ5Y6Lj
            YWgkdrvWQzfnJCph71BHCa1PYiIv9rSL9O1l2rC4pGHHGbmtneZLxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T22:56:55Z"
    mac: ENC[AES256_GCM,data:ivI3R2zkHwjq6UFE3DoKmUSEiTFkPWpDDwRtg8NAoUtr7pmtf8nwUyS1OmxGLw/roGFD2yyEH0Xzf+9ngjDap/iSH5hcioQYMRMvim1v+Enyn4eia0iCBjfbgx4HPT4hTVG79NUFxZJTfoHdg00tWeHF7C3Bt0LkpLqs6TMLlw8=,iv:6YUop/LBFE5510d81Ty5//mXNmhTpbEes5ehd32K18A=,tag:WS6WeZAfz8jJdNqwEub7dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
