apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-private-repo-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: private-repo-creds
          annotations:
            argocd.argoproj.io/secret-type: repo-creds
          stringData:
            type: ENC[AES256_GCM,data:mzLG,iv:p50Z41CP1ko2njXPLsc4H/gE0aAYt5ELMqP1lI06bYU=,tag:o6vbAaX1Jb5xPh1idUCDCQ==,type:str]
            url: ENC[AES256_GCM,data:yDAiqYCe72Km3bNxQcrRPYVSSfGOmRizZAKf,iv:NsdKjWrmIPi9IAko+R3mxK/Ejh2BKh16Fly0vq4ndUc=,tag:2znk0Wk1GjipXdMdrdDaxg==,type:str]
            password: ENC[AES256_GCM,data:5Au4Wzy4z+FXNY4FOyrxK93YTDPbPBWQN0P5Vddc2SHOL6ZC67g2LQ==,iv:tTN43vgmlBqpl8z40LOYeWxV2tPoxEEOu3kuCQaJKIo=,tag:vLMgj5H9ZCXDobkKm0sk4w==,type:str]
            username: ENC[AES256_GCM,data:B/duepuE9vg=,iv:HNrKJaAg9pDqZRr2p2q8rkzENcl3gU3/a6H3BxEnsCA=,tag:z6fMHwWQ4dpzWia4SzX1zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM3g4OGo2bFNYQWZSdC9E
            MzRsWFNrYlBINkhMbjRQZmp4Zi9ndWdJdmtvCmQ0M2REa3Z2RmlGMVg2RFo2Y3dC
            L0tuTlFoRmNjQjRxbVdxVExNMDhhN1kKLS0tIEozRzZrekJNdWswaWtFLzVnVUxZ
            aXhkYWhvNG1WTkpRcDNRQTE0TnovTU0KAOob+1gGQFfglMwZOr3CevKIVRsgukMs
            hz5by4QvatUi8mEB020uQ6PB0cZrKj/Mqf9sj4dX57Vn/MuEYFErUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T04:31:25Z"
    mac: ENC[AES256_GCM,data:FaUXRuktr4PmaGSEzhiPDldkXxFKju/ZD4bZrOeXPVpCysuUKST7vektB3bAV1UnGH5QIzSkjlZPKU2oonOHb+is1SvYs7y7wQA3S7eTQHGMmL740ufI8O1uHfzdv0P6mrTM6G+FJ8pQ8jHTmXgZjuzpKD6O4VonkeNDmpa93Q0=,iv:5pEYy7npwTHsYOyQ3dGkyohyUj4s05eMaGKbK1zqzOM=,tag:IbpKabPnEpLpHeiv2HUCbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
