apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.elposhox.dev`)
    services:
    - kind: Service
      name: argocd-server
      port: 80
          