apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-redis
    namespace: argocd
spec:
    suspend: false
    secretTemplates:
        - name: argocd-redis
          stringData:
            auth: ENC[AES256_GCM,data:p6CJ4jYTWjdpR0qkhcWPjPPY65ho8jUTfNyMHWUCMLAfeA==,iv:88CqKPSuANzRkL8ZWjyYk3+qDX0qCORnnrcqLFYOIEU=,tag:kpVnJPmvQiYO2n3UCLLc8Q==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQzU1eWplQ2VlN2tUTVNP
            Mm5rU0UrWXNyOWZ2RDIxVTFieHBDdDdnTndJCjRTVy9GV25DL2svNzE5SExDZHdG
            dTZSNjZnM0d1ay93aU1vQ0s5SnIyV2MKLS0tIEcyMUdZR0lrZ3BSQUkzYzZBeVZC
            TGxmVWYzSXkxSFdJby9aelA5M0lXNWsKmOq3NX3xmSMvW/+idaStVS8ABNn/dq+g
            KtzrHB7Orl/Jy8L0X3XBCB5LAx8RtKND+05VQRRaxvJF2RBTzzQBAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T22:56:44Z"
    mac: ENC[AES256_GCM,data:TkqVnk20fJOpYza7hVJZ0HmC1KbuP2mXNBD42vbiAJ5eWk9Ts02+3ofwnQcs5mepds3j0RWaUQA+UtJUBULd5YcF1PELvOgAHPdIUNoSVI2cAuJgKT5dP08UOWokdPDc+8xxQx6vmUYHR8ianQZcCQaTjBub5t1De+CRe/7WUJc=,iv:vxLC3JZ72mJXZSdzPbQEPiYzJR27N1u4n39OmkF5Bfk=,tag:6Z9x2umVjMcD5s+itkZqAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
