apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-argocd-private-repos
  namespace: argocd
spec:
  secretStoreRef:
    name: external-secrets-operator-cluster-store
    kind: ClusterSecretStore
  target:
    name: argocd-private-repos
    template:
      engineVersion: v2
      metadata:
          labels:
            argocd.argoproj.io/secret-type: repo-creds
            app.kubernetes.io/name: argocd-private-repos
            app.kubernetes.io/part-of: argocd
          annotations:
            managed-by: argocd.argoproj.io

      data:
        url: https://github.com/Cibahealth
        type: git
        githubAppID: '{{  .github_app_id }}'
        githubAppInstallationID: '{{  .github_app_installation_id }}'
        githubAppPrivateKey: '{{  .github_app_private_key }}'
  data:
  - secretKey: github_app_id
    remoteRef:
      key: /platform/argocd/github-app/app-id
  - secretKey: github_app_installation_id
    remoteRef:
      key: /platform/argocd/github-app/installation-id
  - secretKey: github_app_private_key
    remoteRef:
      key: /platform/argocd/github-app/secret-pem