apiVersion: v1
kind: Secret
metadata:
    name: argocd-redis
    namespace: argocd
type: Opaque
stringData:
    auth: ENC[AES256_GCM,data:fszUGNNxlZijzXYBjN12SIS3FLt2eNzLsVkAGU6N36D+EA==,iv:PeEj71c1Dbqil20bUAxGZupxZbtbyqMPApzeSpFgoBc=,tag:FrwSn+ttChAgC5gYEDLaPw==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRVVIclE1eFBuYllCelh5
            MTNRSmJEZEZtb1d3bjE4TzNrWDA3aXpMdFVFCngrUi9wTzJTTHN3NmY2NlJ0MHdi
            MVFrSERnaEZuV0l4UEU3aFB3TXNUM2MKLS0tIFE1MFFYUXU4R00wekQvWXJBR01T
            M2IxYWUrM0l4eU4rbi9mSGlhYXNoYWsKYq1Jp9mSeEYi4iE1LfjfEj2/UneEv+fA
            wOurgTleYfX9Q6rPvUj1S19RA+3F2QFtkm/nicv0hPE4ozEbZX6/Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T00:33:39Z"
    mac: ENC[AES256_GCM,data:Hm+V0es0WV2JQ7vzblzO6i3V22RNo+lkEcaZ8j7rfhEKidc5vSM7AqxLPtvWpMDCEio+F0Oode4L58EYB7Uyv/82zd7jy/oU6tODYLb7SB0eq3KMR5cDCOwerZqaxcsNojdiYeNJ4ablGBAlGCOICHCP5D4sSTi/7MO540/RhfQ=,iv:02St/NegC7U29+p06gl8a1U4TqFnHhBQy1snwZ/ttnw=,tag:GKO0VSoKhJqYEPiUYCmA0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
