apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-private-repo-secret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: private-repo-creds
          annotations:
            argocd.argoproj.io/secret-type: repo-creds
          stringData:
            type: ENC[AES256_GCM,data:fnC4,iv:Q1FtZym0Ju7XjSVq+JXSjzuYcRJEzMJWnFqBw0N2/6E=,tag:+Yq/SlOd6aLZDUT86kmA+Q==,type:str]
            url: ENC[AES256_GCM,data:MU47Z90aWp0ZEVRKhGz6r5wia86cfaGIUQlE,iv:sNVpz10NOx748UZDbpyX/SxuX2Ngc/doOA2HnIIGQEk=,tag:7/71gcBLmfw7VfhxI5DpEA==,type:str]
            password: ENC[AES256_GCM,data:WM/8ZjLesWcjm/nXskpXH9IehEBlmvZ77TIdIqfVWlEB3uI7mcMZTA==,iv:xB8mSTCKIrELLj1jskCcRWvSauSxQZ8CoG5vMD998s0=,tag:+BhafeyjYo9on2HaNuR3Ug==,type:str]
            username: ENC[AES256_GCM,data:9TIs3TBHxUk=,iv:Y17C0/UPmbLPFTSsfyslWmXvvnUA7zwb2h7tLe+BE14=,tag:TbgCxKq+idP8Cz5ZX6RBvw==,type:str]
sops:
    age:
        - recipient: age1wtl5vlup8jkg5q3mwyed4mx5c8fsezqcd8lennp0qkreckfnupeswjlk3q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZzFsT05DbTJWdGN0RjZP
            M2RpTTlubmEyYjAxTEp1Si9EcG1lWDhiR1YwCk82Y3dlOWpKcktqQzlXcTBJWUw3
            dGhpWTdvTFZsd24vbGVaeUlpYlJDbDgKLS0tIDZhalVDM0Ezc1RFTnRwU0o3RXVj
            MGl2YWFvUEUxWU1xOEdVTitwT01kMkEK0HHwSBhV/HnENc1ENit6193jbZvUE1Yt
            CwxrMvBAX4fxMBQd45oqwmBof+EGMWr572n7sKTG8GXwcff3h18KBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T00:32:28Z"
    mac: ENC[AES256_GCM,data:StjbMfQYSkpmQ2RcR0DgP3U6M6qrQP+GSbtJHBM7JPPJmedlf1H4Oiqpj7v7LKs5kLl+PeeyR7NJ/arvsbgaZkD4AnvDd471TRSxqoZccONPe7y7HMG031Sm6vHqf5jIm2C/eDEPya32pecqruSKbuzGvEgZeM2aV42VlvKXYJU=,iv:s5LqYNQhuscKEI2JmIf86+az9RpLiJZnmaZjrByHAdY=,tag:VCi1/cobmMRwArUmxvmMTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
